theme: jekyll-theme-minimal
title: Bomberman Bot
description: A neural net designed to play the classic bomberman game! Made as a final project for Franklin W. Olin College of Engineering's Software Design 2017
